### ISSUE TITLE
Missing Parameter

### ISSUE THREAD

**Issue by YaderlGears** [manywho/service-sql#15] opened 2017-09-21 19:50 UTC
![save error sn](https://user-images.githubusercontent.com/32177741/30715517-ae35ad0c-9ee4-11e7-96d3-718d3c8228e3.JPG)
Hello,

The issue we're having is with the save element. Whenever we attempt to save data (Error: org.sql2o.Sql2oException: Error in executeUpdate, The value is not set for the parameter number 4.). 

The parameter number changes on the number of values being updated in the database. For example, if our operation has 5 updates to the values, the parameter is 6. If there only 2, then the parameter is 3. 

To us, it looks like the service is expecting a parameter that can't be updated via the flow, but is necessary to actually save the data every time. On the other hand, getting data from the server is working just fine.

Please let us know how to address this issue as soon as possible. I'll be available to answer any questions, even during the UK team's hours as it's highly important that we solve this before the weekend is over.

Thanks for your support and prompt response.

Yaderl
Gears CRM

**Comment by jose-collazzi** [comment] 2017-09-22 07:43
It is very difficult to understand the problem without more information:

Could you please provide:

- database Type (MySql, PostgreSQL or SQL  Server) 
- definition of the table
- values that you are trying to update

**Comment by josecollazzi** [comment] 2017-09-27 11:27
@YaderlGears should I close this issue?

The issue https://github.com/manywho/service-sql/issues/16 have been added to improve error messages.

**Comment by YaderlGears** [comment] 2017-09-29 17:25
Hi Jose,

The issue is still ongoing. We're experiencing it with the DB service, using SQL Server. This is happening across multiple tenants, flows, and tables.

**Comment by josecollazzi** [comment] 2017-10-05 14:45
This issue was caused by setting "Enable Smart Save of data" because it is not currently supported in this service.

**Closed by josecollazzi** 2017-10-05 14:45 UTC
